plugins:
# Disrupting host time
- timeburglar:
   shift: 100
   startup: hot
   frequency: fixed
   interval: PT01S
# Dropping client connection
- dropper:
    target: client
    ip: 10.5.0.10
    unavailable_seconds: 60
    frequency: random
    min_interval: PT05S
    max_interval: PT60S

# Dropping node_exporter container
- deathloop-sh:
    target: node_exporter
    frequency: random
    min_interval: PT05S
    max_interval: PT60S
