plugins:
# Disrupting host time
- timeburglar:
   shift: 100
   startup: hot
   frequency: fixed
   interval: PT10S
# Dropping client connection
- dropper:
    target: client
    ip: backend
    unavailable_seconds: 60
    frequency: random
    min_interval: PT5M
    max_interval: PT10M
# Dropping backend container
- deathloop-sh:
    target: backend
    frequency: random
    min_interval: PT10M
    max_interval: PT20M
