version: '3.4'

services:
  kittypaws:
    container_name: kittypaws
    build: .
    restart: always
    privileged: true
    networks:
      - kittypaws
  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - kittypaws
  backend:
    container_name: backend
    image: networkstatic/iperf3
    entrypoint: /bin/bash
    command: iperf3 -s
    restart: always
    networks:
      - kittypaws
  client:
    container_name: client
    image: networkstatic/iperf3
    entrypoint: /bin/bash
    command: iperf3 -c backend
    restart: always
    networks:
      - kittypaws

networks:
  kittypaws: {}
