version: '3.4'

services:
  kittypaws:
    container_name: kittypaws
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: always
    privileged: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_ADMIN
    networks:
      - kittypaws
  node_exporter:
    container_name: node_exporter
    image: bitnami/node-exporter:1-debian-11
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "127.0.0.1:9100:9100"
    cap_add:
      - NET_ADMIN
    networks:
      - kittypaws
  backend:
    container_name: backend
    image: networkstatic/iperf3
    entrypoint: /bin/bash -c "/usr/bin/apt update -qqy && /usr/bin/iperf3 -s"
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      - kittypaws
  client:
    container_name: client
    image: networkstatic/iperf3
    entrypoint: /bin/bash -c "/usr/bin/apt update -qqy && /usr/bin/iperf3 -c backend -tinf"
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      - kittypaws

networks:
  kittypaws: {}
