scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node_exporter:9100']
  - job_name: docker
    scrape_interval: 5s
    static_configs:
    - targets: ['host.docker.internal:9323']
