name: kittypaws
on: [push]
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
        env:
           SEMGREP_RULES: p/default
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly
      - name: toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: lint
        run: |
          cd src
          cargo fmt -- --check || true
          cargo clippy -- -D warnings || true
      - name: test
        run: |
          cd src
          cargo check
          cargo test --all
      - name: build
        run: |
          cd src
          cargo build --release